events {}

http {
    server {
        listen 80;

        # Serve your static site
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Required for nginx-exporter to collect metrics
        location /stub_status {
            stub_status;
            allow 172.0.0.0/8;   # allow Docker internal network
            deny all;             # block external access
        }
    }
}
